language: node_js
node_js:
- 6.11.0
before_install:
- rvm install 2.3.1
branches:
  only:
  - master
install:
  - npm install -g firebase-tools
  - npm install
  - gem install bundler
  - bundle install --path vendor/bundle
before_deploy:
  - bundle exec jekyll build
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: $FIREBASE_PROJECT
