language: node_js
node_js:
- 6.11.0
before_install:
- rvm install 2.5.1
install:
  - npm install -g gulp-cli
  - npm install
  - gem install bundler
  - bundle install --path vendor/bundle
branches:
  only:
    - master
before_script:
  - export TZ=Asia/Tokyo
script:
  - make
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  project: $FIREBASE_PROJECT
