# Site settings
title:       horimisli.me
email:
author:      horimislime
description: "horimislime's blog"
baseurl:     ""
url:         "https://horimisli.me"
date_format: "%Y/%m/%d"
permalink: /entry/:title/

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: UA-30891696-1
google_tag_manager:
# Bing services
bing_verification:

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username: horimislime
stackoverflow_id: 1430224
twitter_username: horimislime
linkedin_username:
medium_id:
bitcoin_url: https://lh3.googleusercontent.com/-KUkJTrYEkdw/XesXwwlJ0ZI/AAAAAAABXao/o2QT_Rt52K8pZkAKjxwy1dpHr4UhVhqWwCE0YBhgL/btc-wallet.png

# Build settings
markdown:     redcarpet
highlighter: rouge
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
paginate:     10
# https://github.com/penibelst/jekyll-compress-html
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]

# jekyll-seo-tag
twitter:
  username: horimislime
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [
  "vendor",
  ".gitignore",
  "LICENSE.txt",
  "README.md",
  "Rakefile",
  "Gemfile*",
  "Procfile",
  "*.rb",
  "config.ru",
  "*.yml",
  "package*.json",
  "gulpfile.js",
  "node_modules",
  "*.tf*",
  "firebase.json",
  "CNAME",
  "LICENSE",
  "Rakefile"
  ]
