# Site settings
title:       horimislime
email:
author:      horimislime
description: "horimislime's blog"
baseurl:     ""
url:         "https://horimisli.me"
date_format: "%Y/%m/%d"
permalink: /entry/:title/

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: UA-30891696-1
google_tag_manager:
# Bing services
bing_verification:

# Optional features
animated:             true
show_related_posts:   true
show_post_footers:    true
show_social_icons:    true
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: false

# Facebook Page integration
# (for instant articles and other stuff)
fb_page: false
fb_page_id:

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# txtpen post comments
# (leave blank to disable txtpen)
txtpen_sitename:

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username: horimislime
bitbucket_username:
stackoverflow_id: 1430224
twitter_username: horimislime
skype_username:
steam_nickname:
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url: https://lh3.googleusercontent.com/-KUkJTrYEkdw/XesXwwlJ0ZI/AAAAAAABXao/o2QT_Rt52K8pZkAKjxwy1dpHr4UhVhqWwCE0YBhgL/btc-wallet.png
paypal_url:
flattr_button:
telegram_username:
vk_id:

# Post sharing icons
show_sharing_icons: true
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         ''
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting us. We will reply as soon as possible.'
  og_locale: 'ja_JP'

# Build settings
markdown:     redcarpet
highlighter: rouge
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
paginate:     10
sass:
  style: compressed
# https://github.com/penibelst/jekyll-compress-html
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]

# jekyll-seo-tag
twitter:
  username: horimislime
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [
  "vendor",
  ".gitignore",
  "LICENSE.txt",
  "README.md",
  "Rakefile",
  "Gemfile*",
  "Procfile",
  "*.rb",
  "config.ru",
  "*.yml",
  "package*.json",
  "gulpfile.js",
  "node_modules",
  "*.tf*",
  "firebase.json",
  "CNAME",
  "LICENSE",
  "Rakefile"
  ]
