title:       horimisli.me
author:      horimislime
description: "horimislime's blog"
baseurl:     ""
url:         "https://horimisli.me"
date_format: "%Y/%m/%d"
permalink: /entry/:title/
paginate:     10

# jekyll-seo-tag
twitter:
  username: horimislime
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
include: [
  ".well-known"
]
exclude: [
  "functions",
  "vendor",
  "README.md",
  "Gemfile*",
  "Makefile",
  "*.yml",
  "*.json",
  "*.py",
  "LICENSE"
]
