name: blog
description: My personal blog
homepage: https://github.com/horimislime/horimisli.me
environment:
  sdk: ">=2.10.4 <3.0.0"
dependencies:
  universal_html: ^1.2.1
dev_dependencies:
  linter: ^0.1.113
