name: blog
description: My personal blog
homepage: https://github.com/horimislime/horimisli.me
environment:
  sdk: 2.10.4
dependencies:
  args: 1.6.0
  universal_html: ^1.2.1
  markdown: 3.0.0
  mime: 0.9.7
dev_dependencies:
  linter: 0.1.129
