name: blog
description: My personal blog
homepage: https://github.com/horimislime/horimisli.me
environment:
  sdk: ">=2.8.1 <3.0.0"
dependencies:
  html: ^0.14.0+3
dev_dependencies:
  linter: ^0.1.113
