name: Deploy to Firebase Hosting on PR
'on': pull_request
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      # - name: Checkout Articles
      #   uses: actions/checkout@v2
      #   with:
      #     repository: horimislime/articles
      #     token: ${{ secrets.GITHUB_ACCESS_TOKEN || github.token }}
      #     ref: master
      #     path: posts
      # - name: Checkout Images
      #   uses: actions/checkout@v2
      #   with:
      #     repository: horimislime/article-images
      #     token: ${{ secrets.GITHUB_ACCESS_TOKEN || github.token }}
      #     ref: master
      #     path: public/images
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build
        run: |
          npm install
          npm run prod
      # - name: Deploy to Preview Channel
      #   uses: FirebaseExtended/action-hosting-deploy@v0.3-alpha
      #   with:
      #     repoToken: '${{ secrets.GITHUB_TOKEN }}'
      #     firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BLOG_70591 }}'
      #     projectId: blog-70591
      #   env:
      #     FIREBASE_CLI_PREVIEWS: hostingchannels
