name: Deploy to Firebase by Repository Dispatch
'on': 
  repository_dispatch
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Checkout Articles
        uses: actions/checkout@v2
        with:
          repository: horimislime/articles
          token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          path: _posts
      - name: Checkout Images
        uses: actions/checkout@v2
        with:
          repository: horimislime/article-images
          token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          path: images
      - name: Build
        run: make build
      - name: Deploy to Live Channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BLOG_70591 }}'
          channelId: live
          projectId: blog-70591
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
