name: CI

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Set up Ruby 2.5
        uses: actions/setup-ruby@v1
        with:
          version: 2.5.7
      - name: Build
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          make clean build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Publish
        run: make publish
