name: Build and deploy preview
'on': pull_request
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Create posts dir to make build works
        run: |
          mkdir posts
      - name: Build
        run: |
          npm install
          npm run prod
