name: Release
'on':
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Checkout Articles
        uses: actions/checkout@v3
        with:
          repository: horimislime/articles
          token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          path: posts
      - name: Checkout Images
        uses: actions/checkout@v3
        with:
          repository: horimislime/article-images
          token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          path: public/images
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - name: Build
        run: |
          npm install
          npm run prod
      - name: Deploy to Live Channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BLOG_70591 }}'
          channelId: live
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
  notify:
    name: Notify
    needs:
      - build_and_deploy
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Conclusion
        id: conclusion
        uses: technote-space/workflow-conclusion-action@82dd67fd29a53f18f33a99e0bbfb138318a80dcd # renovate: tag=v3.0.4
      - name: Notify
        run: |
          curl \
          -X POST \
          -H 'Content-type: application/json' \
          --data '{"text":"Deploy ${{ steps.conclusion.outputs.conclusion }} \nhttps://horimisli.me"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
